name: Deploy to Azure Web App

on:
  workflow_call:

env:
  REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
  APP_NAME: ${{ secrets.APP_NAME }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  IMAGE_NAME: meuapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Login ACR
        run: az acr login --name $REGISTRY_NAME

      - name: Build and Push Docker image
        run: |
          docker build -t $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:latest .
          docker push $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:latest

      - name: Deploy to Web App
        run: |
          az webapp config container set \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --docker-custom-image-name $REGISTRY_NAME.azurecr.io/$IMAGE_NAME:latest \
            --docker-registry-server-url https://$REGISTRY_NAME.azurecr.io
